#!/bin/bash

echo "🚀 BroConnect GitHub Deployment Guide"
echo "======================================"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'broconnect'"
echo "3. Make it PUBLIC (so you can share with friends)"
echo "4. DON'T initialize with README (we already have one)"
echo "5. Click 'Create repository'"
echo ""
echo "6. Copy the repository URL (it will look like: https://github.com/YOUR_USERNAME/broconnect.git)"
echo "7. Run the following commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/broconnect.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "8. After pushing, go to your repository settings and enable GitHub Pages:"
echo "   - Go to Settings > Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main"
echo "   - Folder: / (root)"
echo "   - Click Save"
echo ""
echo "9. For better deployment, connect to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - Sign up with GitHub"
echo "   - Import your broconnect repository"
echo "   - Deploy automatically"
echo ""
echo "Your app will be live at: https://YOUR_USERNAME.github.io/broconnect"
echo "Or with Vercel: https://broconnect.vercel.app"
